pipeline {
    agent any
    environment {
        RELEASE='0.0.1'
    }
    stages {
        stage ('Build') {
            agent any
            environment {
                LOG_LEVEL='INFO'
            }
            steps {
                echo "Building release ${RELEASE} with log level ${LOG_LEVEL}"
            }
        }
        stage('Test') {
            steps {
                echo "Testing release ${RELEASE} ..."
            }
        }
        stage('Deploy') {
            input {
                message 'Deploy?'
                ok 'Do it!'
                parameters {
                    string(name: 'TARGET_ENVIRONMENT', defaultValue: 'PROD', description: 'Target deployment env')
                }
            }
            steps {
                echo "Deploying ${RELEASE} to env ${TARGET_ENVIRONMENT}"
            }
        }
    }
    post {
        always {
            echo 'Prints wether deploy happend or not, success or failure'
        }
    }
}
